### ISSUE TITLE
Add CongestionLevel: closed

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-directions-swift#164]
The enum value `closed` will soon be made available. We should update this repo preemptively. 

/cc @1ec5 @tcql

**Comment by tcql** [comment]
In order to prevent breaking all existing traffic styles, we've decided to move closures to a new property instead of muddling the purpose of `congestion`. This week, we should be deploying a change that includes `closed=yes`

**Comment by 1ec5** [comment]
@danpat pointed out that OSRM will never route over a closed road, and congestion annotations require the `mapbox/driving-traffic` profile, so there’s no point in providing this value.

**Comment by bradleyrzeller** [comment]
@1ec5 @bsudekum  Can I get a little more info on this? This was closed because supposedly the directions api will never route over a closed road...

However, in my testing, I _am_ getting directions over a closed road...

Example Code:
```
let directions = Directions(accessToken: "foobar")
// source -> dest is closed
let options = RouteOptions(coordinates: [source.coordinate, dest.coordinate])
options.profileIdentifier = .automobile
options.routeShapeResolution = .full
options.attributeOptions = .congestionLevel

directions.calculate(options) { waypoints, routes, error in
      // no error, valid route
      // note the leg contains a bunch of segmentCongestionLevels, all of which are .unknown
}
```

Am I missing something? The road is definitely closed as reported by CalTrans and all other major map service.

**Comment by danpat** [comment]
@bradleyrzeller Can you share specific coordinates?  Our routing engine won't route over a closed road *if it knows the road is closed*.  If you're getting a route, it means we're missing the closure from our data, thus wouldn't be able to report "closed" anyway...

**Comment by bradleyrzeller** [comment]
There's a handful. Lee Vining, CA (37.950585, -119.113731) to Crane Flat Campground, CA (37.748415, -119.800683). Mapbox is routing right over hwy 120 which is closed during the winter.

![img_3182](https://user-images.githubusercontent.com/1642082/51491889-a6918300-1d64-11e9-9deb-d078349718bb.PNG)

Another example is (34.686700, -119.355898) to (34.754349, -119.067458). It routes over Lockwood Valley Rd. which is currently closed to a mudslide.

**Comment by danpat** [comment]
@bradleyrzeller Right - so these are routing engine errors, we shouldn't be providing a route over these roads, they're closed.  I'll add these cases to our internal data queue to look into, I'm not sure why we're missing them.

The original ticket here is about providing a `closed` CongestionLevel value, but that doesn't really make sense to do - if we knew the road was closed, we wouldn't return a route that follows it, so a `closed` `CongestionLevel` would never occur.  The only reason we're routing over these roads is that the backend *doesn't* know they're closed (and thus can't provide a `closed` congestion level).

**Comment by bradleyrzeller** [comment]
Interesting. I'm using the Directions API, not using map matching.

```
let directions = Directions(accessToken: "foobar")
// source -> dest is closed
let options = RouteOptions(coordinates: [leeVining, craneFlat])
options.profileIdentifier = .automobile
options.routeShapeResolution = .full
options.attributeOptions = .congestionLevel

directions.calculate(options) { waypoints, routes, error in
      // no error, valid route
      let route = routes[0]
      let coords = route.coordinates!
      let polyline = MGLPolyline(coordinates: coords, count: UInt(coords.count))

      // add polyline to mapview...
}
```

The first route that the `directions.calculate()` call is returning is over the closed highway.

**Comment by danpat** [comment]
@bradleyrzeller Ah, I see it.  If you change to:

```
options.profileIdentifier = . automobileAvoidingTraffic
```

then you'll get the expected route.

I'm going to open an internal ticket about the non-traffic `mapbox/driving` profile not supporting slow-changing seasonal closures - it's a bug IMO, but this is kind of sitting in a bit of a grey area.

**Comment by bradleyrzeller** [comment]
Oh ok, gotcha. So I think there was just confusion mostly in that _some_ road closures are not noted in your backend. For example, this route is still giving incorrect directions as Lockwood Valley Road is closed right now: (34.686700, -119.355898) to (34.754349, -119.067458). I was trying a few different combinations of the profileIdentifier and different roads that I knew were closed and likely just got mixed results, but this helps a lot, thanks!

Also, I would actually push back on the `mapbox/driving` profile _ever_ respecting road closures. Without getting too into the weeds, our use case is to always be able to get the most direct route between two waypoints. The main reason for this is that "building" the route and "navigating" it are two separate events that can happen at two very different times (e.g. build a route, during the winter, over a closed winter road, to be navigated in the summer). So during the "build" event, we'll use the `automobile` profile and during the navigation event, we'll use the `.automobileAvoidingTraffic` profile. Anyways, that's just my two cents.

Appreciate the help!

**Comment by danpat** [comment]
> build a route, during the winter, over a closed winter road, to be navigated in the summer

This actually does highlight a case that I don't think we considered when closing this ticket: a big time difference between calculating the route and navigating it.

The Map Matching API can be used to fetch "current conditions" along a route - e.g. to update the ETA of an existing route without changing the route itself.  It's definitely conceivable that you could obtain a route over a closed road, and later Map Match it - in this case, I *do* think that a `closed` `CongestionLevel` would be appropriate.

I'm going to re-open this ticket because of this case - we've been seeing more and more uses like this.

There are a few backend pieces that would need to fall in place before it would work, but I do think it's something we need.

**Comment by bradleyrzeller** [comment]
Agreed, that's what led me to this issue in the first place actually. Sounds good and thanks again for the help.

**Comment by 1ec5** [comment]
#713 tracks hooking up support for the `closure` attribute that’s been around for a few years. It works a little differently than the `closed` congestion level suggested above but should be adequate for detecting and displaying these closures.
