### ISSUE TITLE
Improve error messaging when attempting to use 3+ waypoints

### ISSUE THREAD

**Issue by captainbarbosa** [mapbox/mapbox-directions-swift#249]
If a developer attempts to calculate directions with more than three waypoints, the following error is returned: 

```
Error Domain=MBDirectionsErrorDomain Code=-1 "Too many coordinates;
maximum number of coordinates is 3." 
UserInfo={NSLocalizedFailureReason=Too many coordinates;
maximum number of coordinates is 3.}
```

It appears the [Mapbox Directions API](https://www.mapbox.com/api-documentation/#directions) doesn't allow for using more than three waypoints in a directions calculation if the profile is set to `automobileAvoidingTraffic`. It would be useful if this was more clearly stated in the error message.

**Comment by ReSpawN** [comment]
@captainbarbosa Thanks so much for posting this, it completely wrecked my brain searching for a solution.

**Comment by 1ec5** [comment]
We shouldn’t hard-code any profile-specific logic around error messages, because the waypoint limit is configurable per customer. (Talk to your Mapbox sales or support representative for more information.)
