### ISSUE TITLE
Isochrone API

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-directions-swift#296]
The [Isochrone API](https://docs.mapbox.com/api/navigation/isochrone/) requires a new top-level class alongside Directions. Some of the parameters and many of the response properties are visual in nature, reminiscent of MapboxStatic.swift or the map SDK rather than the APIs currently supported by this library, but I don’t see a need to break it out of this library for the time being as long as colors are only specified as hexadecimal triplets.

/cc @ericdeveloper

**Comment by soonerbh** [comment]
Common use case requested for auto: visualize vehicle range based on vehicle data, static and dynamic environmental or map data.  This is applicable to in-car and mobile companion app use cases.

Mockup created by Mapbox UX team:
![image_preview](https://user-images.githubusercontent.com/38898349/45987713-0ab76b00-c041-11e8-93a2-30772378d39f.png)

**Comment by 1ec5** [comment]
In the meantime, as a workaround, developers can use NSURLSession to connect to the API directly. [The response format](https://www.mapbox.com/api-documentation/#isochrone-response-object) is suitable for passing into the map SDK’s `+[MGLShape shapeWithData:encoding:error:]` to more easily create an MGLShapeSource, and the various feature properties can be used as attributes in paint and layout property expressions. For example, `MGLLineStyleLayer.lineColor` can be set to `[NSExpression expressionWithFormat: "CAST(mgl_join({'#', fillColor}), 'UIColor')"]`.

**Comment by 1ec5** [comment]
> [The response format](https://docs.mapbox.com/api/navigation/isochrone/#response-retrieve-isochrones-around-a-location) is suitable for passing into the map SDK’s `MGLShape(data:encoding:error:)` to more easily create an MGLShapeSource, and the various feature properties can be used as attributes in paint and layout property expressions. For example, `MGLLineStyleLayer.lineColor` can be set to `NSExpression(format: "CAST(mgl_join({'#', fillColor}), 'UIColor')")`.

It’s more verbose with map SDK v10 but still possible:

```swift
style.updateGeoJSONSource(withId: "isochrone", geoJSON: responseData)

var layer = LineLayer(id: "isochrone")
layer.source = "isochrone"
layer.lineColor = .expression(Exp(.color) {
    Exp(.concat) {
        "#"
        Exp(.get) { "fillColor" }
    }
})
try style.addLayer(layer)
```
