### ISSUE TITLE
RouteStep parsing fails when directions for cycling require user to dismount bike

### ISSUE THREAD

**Issue by SebastianOsinski** [mapbox/mapbox-directions-swift#413]
**Version: 1.0.0-alpha.1**

Response for `calculate(_: completionHandler:)` sometimes fails to decode, when `RouteOptions`  is `NavigationRouteOptions` with `profileIdentifier` set to `.cycling`. If directions require user to dismount bike, then `mode` field in one of the `RouteStep` parts of response is set to `pushing bike`:

```json
 {
                "intersections": [
                     ...
                ],
                "driving_side": "right",
                "geometry": "sonn`Bafmn_@nLoaA|@{G",
                "mode": "pushing bike", // <-- this
                "maneuver": {
                  "bearing_after": 106,
                  "bearing_before": 57,
                  "location": [
                    17.030257,
                    51.109642
                  ],
                  "modifier": "right",
                  "type": "continue",
                  "instruction": "Turn right to stay on Rynek"
                },
                "weight": 87.4,
                "duration": 87.4,
                "name": "Rynek",
                "distance": 88.6,
                "bannerInstructions": [
                     ...
                ]
              },
```

`RouteStep` does not support this type of mode. `mode` is represented by `TransportType` enum which does not have case for that.

Documentation comment: https://github.com/mapbox/mapbox-directions-swift/blob/cb704e694d7e199871e05f0e7bbff4195ebd1dd7/Sources/MapboxDirections/RouteStep.swift#L45 suggests that `walking` should be returned as mode instead of `pushing bike`

Documentation for Directions API doesn't mention this type of mode: https://docs.mapbox.com/api/navigation/#route-step-object

<img width="743" alt="Screen Shot 2020-02-14 at 10 06 48" src="https://user-images.githubusercontent.com/2934986/74517067-cb2d3f80-4f11-11ea-8618-9e0bbe4bed4e.png">

**Comment by 1ec5** [comment]
Apparently the documentation is incorrect. [OSRM](https://github.com/Project-OSRM/osrm-backend/blob/15f0ca8ddaa35c5b4d93c25afa72e81e1fb40c3e/features/bicycle/pushing.feature#L13) returns `pushing bike` as the `mode`. The plan at some point may have been for the Directions API to transform it to `walking`, but that hasn’t happened. When we rewrote RouteStep in #382, we probably saw this table in the documentation and thought `pushing bike` had gotten replaced by `walking` in Directions API v5 and the `pushing bike` support was only present for v4 compatibility.

We can fix the issue by mapping `pushing bike` to `walking` in the context of the cycling profile. There’s currently an effort underway to transition the cycling profile from OSRM to Valhalla, which lacks support for the bike-pushing mode, so it probably isn’t worth keeping an explicit bike-pushing mode around. Once the API cuts over to Valhalla, this mapping from `pushing bike` to `walking` would become dead code.

/cc @danpaz

**Comment by SebastianOsinski** [comment]
@1ec5 Thank you. Is there some estimate when the transition to Valhalla will be finished? IMO this is pretty serious bug right now, as it prevents SDK users from getting bicycle directions in many cases. Maybe it would be best for now to implement parsing `pushing bike` as `walking` in RouteStep? This should be pretty easy fix - we only need to implement decoding and coding by hand instead of relying on compiler-generated implementation. I can do it if you want

**Comment by 1ec5** [comment]
Yes, a compatibility shim on the client side would be welcome. 👍
