### ISSUE TITLE
Crash when decoding unexpected road class

### ISSUE THREAD

**Issue by hisnhsien** [mapbox/mapbox-directions-swift#447]
Today  Directions crash
step:
1.build open source code .
2. run Example .
3.touch  Directions .
4.Directions Crash.
![image](https://user-images.githubusercontent.com/70002242/90851694-0ff5cf80-e3a8-11ea-9c36-fe424554e199.png)

Yesterday it worked normally.

**Comment by 1ec5** [comment]
The force-unwrap was added in 593efd3d16810cb8f1a4f28c487e5340d0642dff for #382, which made it into v0.31.0.

**Comment by 1ec5** [comment]
> The initializer should be failable, not just throwing.

On second thought, the approach in #450 of throwing an error is quite elegant and I don’t see a problem with it.

**Comment by 1ec5** [comment]
#450 introduces the additional client-side error handling to avoid a crash in the future.
