### ISSUE TITLE
Command line utility for requests and serialization

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-directions-swift#451]
In addition to the existing Example application that runs on iOS, this project should have an example command line tool target that runs on macOS and Linux.

At a minimum, the command line tool would be able to round-trip an arbitrary, JSON-formatted Directions or Map Matching API response through model objects and back to JSON. RouteOptions or MatchOptions properties would need to be specified as command line options and flags, since those properties aren’t part of the API response format. This functionality would enable us to more easily test integration with the API in a headless environment to catch issues like #447. With this functionality in place, it would be trivial to also add the ability to fetch a route from the API and return it as JSON or print out statistics about the route, which could make the tool useful for other mobile QA purposes.

[The command line tool in MapboxSpeech](https://github.com/mapbox/mapbox-speech-swift/blob/master/Sources/MapboxSpeechCLI/main.swift) can serve as a model to follow. It uses [SwiftCLI](https://github.com/jakeheis/SwiftCLI/). To run on Linux, the new target would need to be compatible with SPM. [ArgumentParser](https://github.com/apple/swift-argument-parser/) is another great option, but it only works with SPM, whereas this project is still designed to use either SPM or Carthage internally.

/cc @mapbox/navigation-ios @danpaz

**Comment by Udumft** [comment]
Implementation tracking in [/mapbox-directions-swift/pull/469](https://github.com/mapbox/mapbox-directions-swift/pull/469)

**Comment by 1ec5** [comment]
> To run on Linux, the new target would need to be compatible with SPM.

Tracking Linux support in #484.
