### ISSUE TITLE
Remove DirectionsResult.routeIdentifier property

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-directions-swift#452]
#406 moved the UUID from each individual Route to the RouteResponse, aligning with the Directions API. However, it looks like it kept around a vestigial `DirectionsResult.routeIdentifier` property. We should remove this property. However, if we need to defer this work past v1.0, then we should instead deprecate the property and wait until v2.0 to remove it.

https://github.com/mapbox/mapbox-directions-swift/blob/8438c7ae161568f7424116754463ba4b0f97543a/Sources/MapboxDirections/DirectionsResult.swift#L153-L158 https://github.com/mapbox/mapbox-directions-swift/blob/8438c7ae161568f7424116754463ba4b0f97543a/Sources/MapboxDirections/DirectionsResult.swift#L59

~~By design, this property is no longer set to anything, but there are still unit tests that assert that it is set to a meaningful value. These tests pass because we haven’t updated the test fixtures.~~

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
The postprocessing step imbues each route with its surrounding response’s UUID, so the values do match, even if it’s a code smell to use this vestigial property:

https://github.com/mapbox/mapbox-directions-swift/blob/8438c7ae161568f7424116754463ba4b0f97543a/Sources/MapboxDirections/RouteResponse.swift#L131

**Comment by Udumft** [comment]
Closed by #562
