### ISSUE TITLE
Replace Xcode 10 with Xcode 12 on CI

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-directions-swift#471]
The CircleCI configuration currently builds this library in Xcode 10, which is practically unused and no longer supported by the navigation SDK. Meanwhile, we have no build coverage on Xcode 12, which is the focus of development. We should replace the Xcode 10 build bot with an Xcode 12 one.

Carthage is currently incompatible with Xcode 12: Carthage/Carthage#3019. As a temporary workaround, we’ll need to copy the [wcarthage.sh](https://github.com/mapbox/mapbox-navigation-ios/blob/89f6cf503b1064e80da220c13ab5962c81630d5c/scripts/wcarthage.sh) script originally added in mapbox/mapbox-navigation-ios#2649.

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
Dropping Xcode 10 from CI also implies that Xcode 10 will no longer be supported as a build environment.

**Comment by avi-c** [comment]
CircleCI is updated but we are still getting unrelated errors building MME.

**Comment by avi-c** [comment]
Fixed now with #472. MME errors taken care of by #474
