### ISSUE TITLE
Convert from Directions API URL to RouteOptions

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-directions-swift#476]
This library should have an easy way to convert a Directions API request URL (or perhaps a URLRequest or array of URLQueryItems) to a RouteOptions or MatchOptions object. This conversion would be especially useful when implementing Handoff or Universal Links. It would also be a useful alternative to the JSON input file expected by the command line tool in #469.

Here’s a crude version I wrote once as part of an internal dogfooding application that supports Handoff and Universal Links:

```swift
extension RouteOptions {
    convenience init?(url: URL) {
        let pathComponents = url.pathComponents
        guard pathComponents.count == 6 && pathComponents[1] == "directions" && pathComponents[2] == "v5" else {
            return nil
        }
        
        let waypoints = url.deletingPathExtension().lastPathComponent
            .split(separator: ";")
            .map { $0.split(separator: ",", maxSplits: 1) }
            .map { CLLocationCoordinate2D(latitude: Double($0[1])!, longitude: Double($0[0])!) }
            .map { Waypoint(coordinate: $0) }
        let profileIdentifier = DirectionsProfileIdentifier(rawValue: pathComponents[3..<5].joined(separator: "/"))
        self.init(waypoints: waypoints, profileIdentifier: profileIdentifier)
    }
}
```

/cc @mapbox/navigation-ios

**Comment by LukasPaczos** [comment]
Dropping for reference the Android equivalent of this feature - https://github.com/mapbox/mapbox-java/blob/f09ceb28b0c1a7e71b6ef75953c1ddf0d971ffad/services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java#L689-L722. The Android `RouteOptions` have fields whose serialized names are equal to the Directions API parameter names so we're first parsing the URL into a JSON and then deserializing into the `RouteOptions` object.

**Comment by 1ec5** [comment]
> It would also be a useful alternative to the JSON input file expected by the command line tool in #469.

Tracking as tail work in #692.
