### ISSUE TITLE
Refine route alert types and properties for public consumption

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-directions-swift#482]
This issue tracks tail work regarding the API for route alerts added in #466, based on https://github.com/mapbox/mapbox-directions-swift/pull/466#pullrequestreview-521913167:

* [x] Rename `AdministrationRegion` to `AdministrativeRegion`
* [x] Clarify whether RestStop represents a rest stop or its type
* [x] Document `RouteLeg.incidents`
* [x] Make Incident properties public and document them
* [x] Make `TollCollection.type` public and document it
* [x] Make `RestStop.type` public and document it
* [x] Change Incident timestamp properties to `Date`s and rename them
* [x] Change `Incident.type` and `subtype` to enumerations (?)
* [x] Replace `Incident.geometryIndexStart` and `geometryIndexEnd` with `shapeIndexRange`

Other tail work is tracked in #477 and #478.

/cc @mapbox/navigation-ios @avi-c

**Comment by Udumft** [comment]
Related changes are tracked in [this PR](https://github.com/mapbox/mapbox-directions-swift/pull/506).
