### ISSUE TITLE
Mocked tests don’t run under Swift Package Manager

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-directions-swift#494]
Swift Package Manager skips over several test suites that account for most of the unit tests in this repository, on all platforms, not just Linux. These tests have all been conditionally uncompiled with `!SWIFT_PACKAGE` because linksmt/OHHTTPStubs@563f48d3fab84ef04639649c770b00f4fa502cca doesn’t support Linux or SPM. We’re using this commit off a fork of OHHTTPStubs for AliSoftware/OHHTTPStubs#286, which introduces watchOS support, even though we don’t have a watchOS test target. Meanwhile, OHHTTPStubs v9._x_ does support both Linux and SPM.

This issue affects only `swift test` on the command line, not testing within Xcode, so the primary impact is to continuous integration.

mapbox/MapboxStatic.swift#109 shows that would be straightforward to upgrade to OHHTTPStubs v9._x_, but that’ll require the fix in apple/swift-package-manager#2817, which is in Xcode 12.2 (which is still a release candidate) or an equivalent Swift 5.3 image for Linux.

Here are the affected test suites:

* AnnotationTests
* DirectionsCredentialsTests
* DirectionsTests
* Most of MatchTests
* OfflineDirectionsTests
* RoutableMatchTest
* Most of RouteRefreshTests
* V5Tests
* VisualInstructionsTests

/cc @mapbox/navigation-ios

**Comment by frederoni** [comment]
> This issue affects only swift test on the command line, not testing within Xcode, so the primary impact is to continuous integration.

A potential workaround for this could be to remove/rename the `.xcodeproj` before testing.
If `xcodebuild` doesn't find a workspace or a project, it defaults to `Package.swift`. I'd argue that it's cleaner and more convenient if you want to test a target OS that differs from the host OS. Instead of passing flags like these to swiftc,
```
-Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios13.0-simulator"
```
we could:
https://github.com/mapbox/mapbox-events-ios/blob/9cefee052e846179addefeca3646e066b582c240/.circleci/config.yml#L27-L32
```swift
mkdir temp && mv MapboxMobileEvents.xcodeproj temp
xcodebuild -scheme MapboxMobileEvents test -destination "platform=iOS Simulator,name=iPhone 11,OS=latest"
mv temp/MapboxMobileEvents.xcodeproj . && rm -rf temp
```

Long term `swift test` should ofc run the full test suite on macOS/Linux, but for testing iOS/watchOS/iPadOS, `xcodebuild` is much more convenient.

**Comment by azarovalex** [comment]
Looks like OHHTTPStubs don't have Linux support, it lacks LinuxMain.swift file, and even if I generate it, OHHTTPStubs imports `Foundation` and `objc/runtime.h` internally. In theory, we can use [open-sourced Foundation written in Swift](https://github.com/apple/swift-corelibs-foundation) on Linux, but we definitely don't have objc runtime there. OHHTTPStubs uses runtime to swizzle URLSesson methods [here](https://github.com/AliSoftware/OHHTTPStubs/blob/e37b05e0ea4916611c08babe7c68211c4de52a38/Sources/OHHTTPStubs/HTTPStubs%2BNSURLSessionConfiguration.m).

OHHTTPStubs on macOS through SMP works fine, there is a minor problem with module names – when we import OHHTTPStubs through Carthage, the name of the module is `OHHTTPStubs`, and when through SMP, the name is `OHHTTPStubsSwift`.  Even though the content of the modules is the same. Currently I'm solving this issue with conditional compilation like this:
```swift
import OHHTTPStubs
#if SWIFT_PACKAGE
import OHHTTPStubsSwift
#endif
```
