### ISSUE TITLE
RouteStep exitIndex not filled with roundabout

### ISSUE THREAD

**Issue by Juju31Fr** [mapbox/mapbox-directions-swift#508]
Hello all,

According to documentation, exitIndex should indicate the number of exits from the approach to the recommended outlet when the maneuver is a roundabout.
From my experience, this is not working and exitIndex is always nil.

**Comment by FestiFete** [comment]
I have the same issue but no answer yet... :(

https://github.com/mapbox/mapbox-navigation-ios/issues/2742

**Comment by S2Ler** [comment]
@Juju31Fr @FestiFete Thanks for the bug report! I was able to reproduce the issue, so we are halfway through the way to make it fixed in the next release.

**Comment by S2Ler** [comment]
This should also fix mapbox/mapbox-navigation-ios#2742
