### ISSUE TITLE
Replace interactive map view with step table in example application

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-directions-swift#523]
Mapbox Directions example application should be updated to Mapbox Maps SDK v10.

**Comment by 1ec5** [comment]
Map SDK v10 introduces a more onerous installation process. The example application doesn’t really make use of the map SDK, so I’m thinking it would be less of a hassle and more maintainable to migrate the example application to MapboxStatic.swift instead.

**Comment by 1ec5** [comment]
> The example application doesn’t really make use of the map SDK, so I’m thinking it would be less of a hassle and more maintainable to migrate the example application to MapboxStatic.swift instead.

Or even remove the map entirely in favor of a table view that can present the information that’s currently relegated to standard output.

**Comment by S2Ler** [comment]
Fixed in #548

**Comment by S2Ler** [comment]
Further improvements tracked in #549
