### ISSUE TITLE
Investigate adding missing Intersection properties to equatable

### ISSUE THREAD

**Issue by jill-cardamon** [mapbox/mapbox-directions-swift#527]
In the Equatable extension of `Intersection`, a few of the struct's properties were not included (specifically `restStop`, `regionCode`, and the `RoadClass`). Could we add these properties into the extension or was their exclusion intentional?

cc/ @Udumft for clarification

**Comment by Udumft** [comment]
I think those are not included to `Equatable` by mistake. I don't see any reason to keep them away.

**Comment by jill-cardamon** [comment]
Awesome thanks I'll add them back in.
