### ISSUE TITLE
Preferred lane direction should be a ManeuverDirection, not a LaneIndication

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-directions-swift#534]
`Intersection.validIndication` and the `preferredDirection` associated value of `VisualInstruction.Component.lane(indications:isUsable:preferredDirection:)` are of type `LaneIndication` as of #529. But `LaneIndication` is an option set containing zero or more indications, whereas this property and associated value need to represent one and only one indication. `ManeuverDirection` has the same cases as `LaneIndication` but is always a single value. That would allow us to avoid the hack in https://github.com/mapbox/mapbox-directions-swift/pull/529#discussion_r606454612 https://github.com/mapbox/mapbox-directions-swift/pull/532#discussion_r607267571 and also allow the navigation SDK to avoid having to convert from `LaneIndication` to `ManeuverDirection` in places where it’s already using the primary maneuver direction to influence lane arrow highlighting.

https://github.com/mapbox/mapbox-directions-swift/blob/399d28ca1c7306a0188d4368bf4b86af2ab9e8e4/Sources/MapboxDirections/VisualInstructionComponent.swift#L77

This change would need to take place in v2.0.0 to avoid breaking backwards compatibility.

/cc @mapbox/navigation-ios

**Comment by zugaldia** [comment]
> This change would need to take place in v2.0.0 to avoid breaking backwards compatibility.

Let's prioritize this work to make sure we don't miss the window.

/cc: @truburt

**Comment by jill-cardamon** [comment]
PR for this ticket: #535
Double checking tests with Directions API response now.
