### ISSUE TITLE
Enable automatic test discovery on Linux

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-directions-swift#539]
As of apple/swift-package-manager#3053 and [Swift 5.4](https://swift.org/blog/swift-5-4-released/), SPM now supports automatic test discovery on Linux. LinuxMain.swift is now deprecated. We should remove that file and XCTestManifests.swift to take advantage of automatic test discovery, which will eliminate the need to maintain a list of tests by hand.

https://github.com/mapbox/mapbox-directions-swift/blob/2ffc5f0cf9cc5a912d6d2187de854931ed79ab7e/CONTRIBUTING.md#L57

We’ll need to wait until Swift 5.4 makes it into [an Xcode image on CircleCI](https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions) before we can depend on these changes:

https://github.com/mapbox/mapbox-directions-swift/blob/2ffc5f0cf9cc5a912d6d2187de854931ed79ab7e/.circleci/config.yml#L42

/cc @mapbox/navigation-ios

**Comment by S2Ler** [comment]
Fixed in https://github.com/mapbox/mapbox-directions-swift/pull/547
