### ISSUE TITLE
Replace SwiftCLI with Swift Argument Parser

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-directions-swift#600]
#469 uses [SwiftCLI](https://github.com/jakeheis/SwiftCLI/), but [Swift Argument Parser](https://github.com/apple/swift-argument-parser/) has an even more elegant API that would facilitate future enhancements to this tool.

Technically, replacing the dependency would be a backwards-incompatible change. If we can take care of the migration by v2.0.0, that would be great. However, we probably have some additional leeway. I don’t expect that any developer would be using the command line tool as a helper process for another command line tool, and even if they did, that other command line tool can still depend on SwiftCLI; it just couldn’t depend on an incompatible 0._x_ version of Swift Argument Parser.

Thanks to @azarovalex for the suggestion.

/cc @mapbox/navigation-ios

**Comment by azarovalex** [comment]
If we leave the same flags as before, will it be still backward-incompatible?
I think SwiftCLI is part of the internal implementation.

**Comment by 1ec5** [comment]
It is part of the internal implementation, but it’s conceivable that a developer could use Carthage to build a command line tool that uses this command line tool as a helper. Their Cartfile might also depend on apple/swift-argument-parser. It’s only a theoretical concern, though, so it would be OK to push this work to v2.1 if it doesn’t fit in v2.0.

**Comment by 1ec5** [comment]
Does Swift Argument Parser support Carthage? If not, this would be a backwards-incompatible change because the command line tool currently builds with Carthage too. Maybe we should frontload eliminating the command line tool’s Carthage support in v2.0.0 in that case.
