### ISSUE TITLE
Add layer property to Waypoint

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-directions-swift#652]
The Waypoint class should have an optional, integer-typed `layer` property corresponding to the [`layers`](https://docs.mapbox.com/api/navigation/directions/#retrieve-directions) URL query parameter.

/ref mapbox/mapbox-navigation-android#4800
/cc @mapbox/navigation-ios

**Comment by jill-cardamon** [comment]
Fixed by #745.
