### ISSUE TITLE
Decoding Directions.Route object requires CodingUserInfoKey.options

### ISSUE THREAD

**Issue by JanTG1** [mapbox/mapbox-directions-swift#659]
I am having trouble decoding a route object from Mapbox Directions. I am encoding a route object like this: 
`//Encode route response Object to pass it to Defaults
                do {
                    // Create JSON Encoder
                    let encoder = JSONEncoder()
                    // Encode Note
                    let encodedRoute = try encoder.encode(route)
                    // Write/Set Data
                    UserDefaults.standard.set(encodedRoute, forKey: "routeObject")
                    print("Encoded route Object.")
                } catch {
                    print("Unable to Encode route (\(error))")
                }`

and decoding it as such: 
`        if let encodedRoute = UserDefaults.standard.data(forKey: "routeObject") {
            do {
                // Create JSON Decoder
                let decoder = JSONDecoder()
                // Decode Note
                myRoute = try decoder.decode(MapboxDirections.Route.self, from: encodedRoute)
                print("Successfully decoded route Object!")
            } catch {
                print("Unable to Decode route. Error: \(error)")
            }
        }`

The error says RouteOptions are missing. I have found that I need to add a decoder.underInfo, so for example `decoder.underInfo = [CodingUserInfoKey.options : x]`, but I have no Idea what x should be. I need some kind of key. Is this supposed to be this way and if so, how can I decode it?

**Comment by 1ec5** [comment]
`options` should be set to an instance of RouteOptions or MatchOptions for a Route derived from the Directions API or the Map Matching API, respectively. The options object should match the options that you used when originally requesting the routes. This information primarily determines how the route geometry has been or will be encoded within the JSON.

**Comment by MaximAlien** [comment]
@JanTG1, closing this one. Feel free to re-open if you have any other questions.
