### ISSUE TITLE
Directions.calculateRoutes(matching:completionHandler:) does not provide map matching values/locations

### ISSUE THREAD

**Issue by Subhashini2610** [mapbox/mapbox-directions-swift#661]
I am having trouble drawing a polyline consisting of waypoints received from my custom server. The polyline received from Directions.calculateRoutes only joins the first two waypoints. I have a total of 27 points that I feed into the Directions.calculateRoutes API. Below is my full code:
```
//custom server to fetch waypoints
        NetworkManager.shared.getRoute(startLon: 9.1407, startLat: 48.6980, endLon:9.0074, endLat: 48.6845) { [unowned self] routeResponse, error in
            if (error != nil) {
                debugPrint("Error in fetching route: \(String(describing: error?.description))")
            } else {
                debugPrint("Route received")
                if let route = routeResponse?.route {
                    
                    var lineCoordinates = []
                    var locationCoords = [CLLocationCoordinate2D]()
                    
                    for location in route {
                        let waypoint = Waypoint(coordinate: CLLocationCoordinate2DMake(location.lat, location.lon))
                        locationCoords.append(CLLocationCoordinate2DMake(location.lat, location.lon))
                        waypoint.separatesLegs = true
                        lineCoordinates.append(waypoint)
                    }
                    
                    let options = MatchOptions(waypoints: lineCoordinates, profileIdentifier: .automobile)//waypoints stored in lineCoordinates array 
                    options.includesSteps = true
                    
                    var routeDetailedCoordinates = [CLLocationCoordinate2D]()

                    
                    _ = Directions.shared.calculateRoutes(matching: options, completionHandler: { [unowned self] session, result in
                        switch result {
                        case .failure(let error):
                            print(error.localizedDescription)
                        case .success(let response):
                            guard let route = response.routes?.first else {
                                return
                            }
                            
                            for leg in route.legs {
                                for step in leg.steps {
                                    if let coordinates = step.shape?.coordinates {
                                        for point in coordinates {
                                            routeDetailedCoordinates.append(CLLocationCoordinate2DMake(point.latitude, point.longitude))
                                            
                                        }
                                    }
                                    
                                }
                            }
                            
                            
                            //plot server points on map
                            let pointAnnotationManager = mapView.annotations.makePointAnnotationManager(id: UUID().uuidString, layerPosition: nil)
                                     
                            var waypointsArray = [PointAnnotation]()

                            for coord in lineCoordinates {
                                var customPointAnnotation = PointAnnotation(coordinate: coord.coordinate)
                                customPointAnnotation.image = .init(image: UIImage(named: "map-marker")!, name: "map-marker")

                                waypointsArray.append(customPointAnnotation)
                            }
                             
                            pointAnnotationManager.annotations = waypointsArray
                            
                            
                            //draw polyline route on map
                            var lineAnnotation = PolylineAnnotation(lineCoordinates: routeDetailedCoordinates)
                            
                            // Customize the style of the line annotation
                            lineAnnotation.lineColor = StyleColor(red: 9, green: 132, blue: 255, alpha: 1.0)
                            lineAnnotation.lineOpacity = 0.8
                            lineAnnotation.lineWidth = 4.0
                            
                            let lineAnnnotationManager = mapView.annotations.makePolylineAnnotationManager(id: "lineAnnotations", layerPosition: nil)
                            lineAnnnotationManager.annotations = [lineAnnotation]
                            
                            //set the bounding box
                            let insets = UIEdgeInsets(top: 24, left: 24, bottom: 24, right: 24)

                            let camera = mapView.mapboxMap.camera(for: locationCoords, padding: insets, bearing: nil, pitch: nil)
                            self.mapView.mapboxMap.setCamera(to: camera)
                            
                        }
                    })
                                            

                    }
                }
            }
```
**Note: The same code was working for the same waypoints until a week back, but now I have stumbled upon this problem.**
This is the polyline being drawn currently(note the waypoints are annotated):
![IMG_8417](https://user-images.githubusercontent.com/54573581/156992752-42ae8021-f85e-4788-8557-3df0f53ea4a0.PNG)

**Comment by andreas-ullrich** [comment]
I have the same problem.

**Comment by 1ec5** [comment]
> I have a total of 27 points that I feed into the Directions.calculateRoutes API. 

Can you provide these points? Better yet, please provide the result of evaluating the following expressions:

```swift
Directions.urlRequest(forCalculating: options).url
Directions.urlRequest(forCalculating: options).httpBody
```

Thanks!

**Comment by 1ec5** [comment]
By the way, it looks like your MatchOptions object only has the `includesSteps` option set. That’s correct, but if you want to subsequently use the route for turn-by-turn navigation, you may also want to set a few more options like `routeShapeResolution` to `full`. For reference, [here’s what the navigation SDK’s NavigationMatchOptions subclass sets by default](https://github.com/mapbox/mapbox-navigation-ios/blob/23650486c63d855b50887d6bd5075d3f336c9324/Sources/MapboxCoreNavigation/NavigationRouteOptions.swift#L137-L143).

**Comment by andreas-ullrich** [comment]
@1ec5 I work with @Subhashini2610 on this problem and can provide the points now but she will provide the evaluation of 
```
Directions.urlRequest(forCalculating: options).url
Directions.urlRequest(forCalculating: options).httpBody 
```
Later because of the time difference.

Here are the points;

```
   counter       lon       lat
1        0 11.829831 48.110075
2        1 11.829680 48.108040
3        2 11.815280 48.082430
4        3 11.771550 48.056500
5        4 11.856080 47.994400
6        5 11.864590 47.976080
7        6 11.867970 47.938820
8        7 11.884170 47.930030
9        8 11.914720 47.930780
10       9 11.931860 47.922260
11      10 11.927660 47.912290
12      11 11.953890 47.882480
13      12 11.988230 47.864970
14      13 11.987400 47.859740
15      14 11.995760 47.854520
16      15 12.010610 47.851440
17      16 12.011450 47.783870
18      17 12.016640 47.773350
19      18 12.054920 47.762110
20      19 12.077240 47.763950
21      20 12.108740 47.779320
22      21 12.150380 47.782850
23      22 12.163190 47.802610
24      23 12.155990 47.833490
25      24 12.164340 47.840610
26      25 12.201080 47.837890
27      27 12.207470 47.839370

```

Thank you!

**Comment by Subhashini2610** [comment]
@1ec5: @andreas-ullrich and I are working together on this topic. In addition to the points he has provided, please find the url request parameters below:

**Directions.urlRequest(forCalculating: options).url**
```
https://api.mapbox.com/matching/v5/mapbox/driving/11.8298,48.1101%3B11.8297,48.108%3B11.8153,48.0824%3B11.7715,48.0565%3B11.8561,47.9944%3B11.8646,47.9761%3B11.868,47.9388%3B11.8842,47.93%3B11.9147,47.9308%3B11.9319,47.9223%3B11.9277,47.9123%3B11.9539,47.8825%3B11.9882,47.865%3B11.9874,47.8597%3B11.9958,47.8545%3B12.0106,47.8514%3B12.0114,47.7839%3B12.0166,47.7734%3B12.0549,47.7621%3B12.0772,47.764%3B12.1087,47.7793%3B12.1504,47.7829%3B12.1632,47.8026%3B12.156,47.8335%3B12.1643,47.8406%3B12.2011,47.8379%3B12.2075,47.8394.json?geometries=polyline&overview=simplified&steps=true&language=en_IN&tidy=false&access_token=myAccessToken
```
**Directions.urlRequest(forCalculating: options).httpBody**
```
nil
```

The URL length is 720, which is why the request is not converted to POST, and hence the httpBody is nil. This is what I could deduce based on your documentation for MaximumURLLength as per AWS quotas (_Maximum length of an HTTP request URL for the purposes of switching from GET to POST._)

Thanks in advance for the help!!

**Comment by danpat** [comment]
The map-matching API is not really appropriate for this use-case.  It is primarily designed to snap a high-frequency (1-0.1 Hz) recording of GPS positions to the road network.  It has some fuzzy logic in it, so the spacing of coordinates can be stretched out and it still works quite well, but looking at your data, you have multiple kilometers of gaps between points - this absolutely breaks the model and intent of "map matching", and what you're seeing is the result of the algorithm not being able to settle on a confident path between your points, because there are too many alternatives.

You should provide more frequent points along your route, or switch to the Directions API and use your supplied points as silent waypoints along that route.

**Comment by danpat** [comment]
@Subhashini2610 For doing that kind of thing, then yes, Map Matching is the way to do it, but you need to provide a lot more resolution than you're currently supplying.

Assuming you have full resolution geometry from your custom server, what I would do is this:

  1. Take the full geometry from your custom server, and sub-sample it into 50m chunks (use something like https://turfjs.org/docs/#lineChunk to achieve this).  This gives you a new sequence of coordinates that follow the original path at regular intervals - this is important to break up potentially very long lines in your custom route.
  2. Use a line simplification algorithm to remove the unnecessary straight-line points - I wrote https://github.com/mapbox/geosimplify-js a while back to do this.  It differs from traditional line-simplification algorithms in that it will not eliminate all points along very long straight stretches - a requirement to use a map-matching algorithm like the Mapbox Map Matching API.
  3. Pass the _simplified_ line geometry to the Map Matching API.  The number of points will be variable, if you need support for very long routes with high numbers of coordinates, please contact Mapbox Sales, they can work with you on supporting that case, we have done it in the past.  If you need exact route following over very long distances, there isn't any other option.

**Comment by Subhashini2610** [comment]
@danpat Thanks for your suggestion. We are trying with more number of waypoints and the chunk based approach. Prima facie it seems to work. We would be testing with more samples.

One question though: Would this still create a problem in turn-by-turn navigation? More so, because NavigationRouteOptions only accepts a max of 25 waypoints and if our server is providing more number of waypoints, we will have to follow the chunk based approach during real time navigation. I will have to keep track of when I am approaching a waypoint and accordingly update the process. Am I correct here or is there something I am missing here?

Also, is there a way to know when a silent waypoint is being approached? I do not want the user to be notified of my waypoints as they are purely route-determiners and not stops. 

I understand that the following delegates will work for non-silent waypoints only. Am I right here?
```
navigationViewController(_ navigationViewController: NavigationViewController, didArriveAt waypoint: Waypoint)
navigationViewController(_ navigationViewController: NavigationViewController, willArriveAt waypoint: Waypoint, after remainingTimeInterval: TimeInterval, distance: CLLocationDistance)
```

Thank you very much for your patience and support.

**Comment by 1ec5** [comment]
> NavigationRouteOptions only accepts a max of 25 waypoints

This is a server-side default limit in the Mapbox Directions API, but your workflow isn’t using the Directions API. NavigationRouteOptions itself does not enforce this limit on the client side.

> My understanding is that waypoint.separatesLegs determines whether or not the point should be considered a silent waypoint. Currently it is set to true. Does making it false suffice or do I need to make some modifications in the way I parse the response from Directions API?

> Also, is there a way to know when a silent waypoint is being approached? I do not want the user to be notified of my waypoints as they are purely route-determiners and not stops.

The navigation SDK will ignore any silent waypoint (that is, any waypoint with `separatesLegs` set to `false`) for the purpose of visual or spoken guidance instructions. The NavigationViewControllerDelegate methods will not be called for a silent waypoint. Silent waypoints only influence the route geometry.

**Comment by Subhashini2610** [comment]
@1ec5 

We will definitely get in touch with the Mapbox support team. But before that, we would also like to see if there are any similar queries on the Mapbox Navigation repo as well.

Thanks a lot for your immediate responses and support so far.

**Comment by Subhashini2610** [comment]
Just FYI: This is the response of **_Directions.shared.calculate(options)_** (options being of type NavigationRouteOptions)
<img width="588" alt="157595546-a7e1db56-b16d-4531-a2bf-8f68b70629c8" src="https://user-images.githubusercontent.com/54573581/157595911-a60b8ae7-d2f2-41c7-b7e1-615b1d3c8c9f.png">

**Comment by danpat** [comment]
@Subhashini2610 Yes, that is a server-side enforced limit.  The default limit for a Directions API request is 25 coordinates.  For Map Matching, it is 100 coordinates.

These limits can be raised for certain use-cases (like this one) by contacting support.
