### ISSUE TITLE
Document that avoiding tunnels is unsupported

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-directions-swift#665]
`RouteOptions.roadClassesToAvoid` accepts any value in `RoadClass`, including `tunnel`, but the Directions API doesn’t support excluding tunnels in its `exclude` parameter.

Originally, in #154, the assumption was that intersections.classes would only ever indicate classes that the request could exclude. Project-OSRM/osrm-backend#4812 broke this assumption, adding `tunnel` as a class but not an excludable class. #237 effectively added it as both.

We’ll eventually need to decouple the `exclude` parameter from the concept of road classes, due to changes like #662, but we can’t formally do that until v3.0.0 due to backwards compatibility concerns. For the time being, we’ll have to settle for updating this documentation comment to note that the option can only be used in the context of `Intersection.outletRoadClasses`, not `RouteOptions.roadClassesToAllow` or `roadClassesToAvoid`:

https://github.com/mapbox/mapbox-directions-swift/blob/2db7fda6029a7c9987cfb9fc7975061891820ca3/Sources/MapboxDirections/RoadClasses.swift#L49-L54

We could also actively omit `tunnel` when converting RouteOptions to a request URL, but it doesn’t look like we do that for any other option that’s supported by only one of `RouteOptions.roadClassesToAllow` or `roadClassesToAvoid`. In general, we try to avoid client-side enforcement of server-side constraints, in case the Directions API relaxes those constraints in a future deployment or conditionally by user.

/ref mapbox/mapbox-java#709

**Comment by azarovalex** [comment]
The PR with documentation update was merged
