### ISSUE TITLE
DirectionsOptions.swift:2:8: error: no such module 'Polyline'

### ISSUE THREAD

**Issue by nastasiupta** [mapbox/mapbox-directions-swift#668]
`../Library/Developer/Xcode/DerivedData/Motour-fplzlrfbzdkuifcohilnsdrryyit/SourcePackages/checkouts/mapbox-directions-swift/Sources/MapboxDirections/DirectionsOptions.swift:2:8: error: no such module 'Polyline'
import Polyline
       ^
Command EmitSwiftModule failed with a nonzero exit code`
I added the Mapbox SDK using SPM.
I have this issue on XCode Version 13.3 (13E113). 
1) I tried the following steps even with the Polyline SDK added separated to the project using SPM
2) I tried to remove `Package.resolve` file multiple times from `project.xcworkspace`
3) File -> Packages -> Reset Packages Caches
4) File -> Packages -> Resolve Packages Versions
5) File -> Packages -> Update to the latest versions
6) Cleaning the project many times before using any of the methods above
7) Delete all `Derived Data`, and clean the project and the methods above.

First I tried with SDK version 2.3.0. After that I downgraded to 2.2.0 (which worked on older XCode versions) and I'm facing the same issue, even in the Package Dependencies I can see that Polyline SDK is there (v5.0.3)

**Comment by nastasiupta** [comment]
CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'mapbox-directions-swift' from project 'MapboxDirections')

**Comment by nastasiupta** [comment]
I created a new project and I included 
https://github.com/mapbox/mapbox-navigation-ios.git
https://github.com/mapbox/mapbox-directions-swift.git

Same issue at build time
https://drive.google.com/file/d/1fpTn3ix2x0huETVOkvDBt91-bie6VEsP

**Comment by MaximAlien** [comment]
@nastasiupta, sorry for a late reply. `MapboxNavigation` internally already uses `MapboxDirections`, is it your intent to link `MapboxDirections` separately? I've just tried to link `MapboxNavigation` in test app and it works fine:

<img width="675" alt="Screen Shot 2022-05-27 at 8 45 06 AM" src="https://user-images.githubusercontent.com/1496498/170733719-4c44568a-2d9e-4074-bd9e-80ccf6fb5c6e.png">
