### ISSUE TITLE
Warn when a pull request changes the public API

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-directions-swift#683]
A CI bot should automatically diff the public API in each pull request with a baseline commit. If the pull request changes the public API in a backwards incompatible manner, the bot should automatically post a comment warning about the breakage. mapbox/mapbox-navigation-ios#3103 implemented this workflow for the navigation SDK, but this library is subject to a similar backwards compatibility guarantee and should benefit from the same guardrail.

/cc @mapbox/navigation-ios

**Comment by bamx23** [comment]
@1ec5 I believe it was added just recently by @S2Ler: https://github.com/mapbox/mapbox-directions-swift/pull/677

**Comment by 1ec5** [comment]
Ah, that explains why it didn’t show up in #684. 👍
