### ISSUE TITLE
Add traffic control device flags to Intersection

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-directions-swift#686]
The Directions API now [includes](https://docs.mapbox.com/api/navigation/directions/#route-step-object) new Boolean-typed properties in intersection objects that indicate which traffic control devices are present at the intersection.

* `railway_crossing`
* `traffic_signal`
* `stop_sign`
* `yield_sign`

Corresponding properties should be added to the Intersection struct, named in camel case per Swift conventions.

/cc @mapbox/navigation-ios

**Comment by Udumft** [comment]
Resolved by https://github.com/mapbox/mapbox-directions-swift/pull/706
