### ISSUE TITLE
Command line tool should accept URL as input

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-directions-swift#692]
The command line tool should accept a Mapbox Directions API request URL as input instead of a JSON file. This functionality was previously implemented in #580, which was obsoleted by #655.

/ref #476
/cc @jill-cardamon @Udumft

**Comment by purew** [comment]
Overarching design goal here should be do this as close to how customers do it as possible. We will use this as a mechanism to evaluate a large set of test-routes against the sdk + nav-api's.

We'll want to run several sdk-cli versions against the golden routes so it also needs to be somewhat easy for the user of this tool to feed similar (the same?) requests to different sdk-cli versions.
