### ISSUE TITLE
Estimated Time of Arrival at Waypoint

### ISSUE THREAD

**Issue by JanTG1** [mapbox/mapbox-directions-swift#719]
While looking for a way to get the eta for a certain waypoint along a route, I found that it is pretty complicated right now. The only way I found was to calculate it myself using the current date and add the expected travel time from now for each leg until I get to the correct waypoint.

Is there a way to get the eta for a certain Waypoint directly? This might be a useful feature for many implementations. It would also be interesting to be able to display that time to the nav ui.

**Comment by 1ec5** [comment]
The navigation SDK’s [RouteProgress](https://docs.mapbox.com/ios/navigation/api/2.6.0/Classes/RouteProgress.html#/Leg%20Statistics) class has some conveniences for this kind of thing, but MapboxDirections tends to stick to functionality that’s provided by the Directions API itself.

> Is there a way to get the eta for a certain Waypoint directly?

Each route leg goes from one waypoint to the next, so this snippet gets you the expected travel time from the origin to the intermediate waypoint at index `waypointIndex`, and you can modify it to compute other statistics instead:

```swift
route.legs.prefix(waypointIndex).map(\.expectedTravelTime).reduce(0, +)
```

> It would also be interesting to be able to display that time to the nav ui.

That does sound interesting. Would you mind elaborating on this idea in a new issue in https://github.com/mapbox/mapbox-navigation-ios/issues/? Thanks!
