### ISSUE TITLE
Making `RouteResponse` `Equatable` and the `identifier/uuid` value 

### ISSUE THREAD

**Issue by sundeepgupta** [mapbox/mapbox-directions-swift#731]
What is the suggested approach to making `RouteResponse` `Equatable`? 

Would it make sense to simply compare its [`identifier`](https://github.com/mapbox/mapbox-directions-swift/blob/50d0941eb1ee3f5820b37bbbfc7d61d7c32ebb50/Sources/MapboxDirections/RouteResponse.swift#L17), which is the `uuid` in the `Directions.calculate` JSON payload?

Is this field ever expected to be `nil`?

**Comment by jill-cardamon** [comment]
Hi @sundeepgupta! To make `RouteResponse` truly `Equatable`, you would need to extend `RouteResponse`  (and its affiliated properties that also aren't `Equatable`) to conform to the `Equatable` protocol. I would not recommend comparing the identifiers since it isn't guaranteed that you can reliably distinguish responses solely on that property. However, comparing other properties in the response should work.

**Comment by sundeepgupta** [comment]
Hi @jill-cardamon, thanks for the reply. Understood - I will look into your suggestion. 

Can you tell me more about the identifier and what it represents? Also, the Swift code declares is as optional. Under what scenario is it expected to be `nil`?

**Comment by jill-cardamon** [comment]
@sundeepgupta Of course. The identifier is generated by the Directions API and represents a unique ID for the request. Every response should have a different value.

The identifier should always be populated with something, but the exceptions are [initializing a `RouteResponse` object from a `MapMatchingResponse`](https://github.com/mapbox/mapbox-directions-swift/blob/50d0941eb1ee3f5820b37bbbfc7d61d7c32ebb50/Sources/MapboxDirections/RouteResponse.swift#L91) and potentially offline generated routes (I can clarify this case). We also don't provide an identifier when initializing a `RouteResponse` in some of our [tests](https://github.com/mapbox/mapbox-directions-swift/blob/50d0941eb1ee3f5820b37bbbfc7d61d7c32ebb50/Tests/MapboxDirectionsTests/RouteResponseTests.swift#L24-L27).

**Comment by sundeepgupta** [comment]
Thanks. If I understand correctly, if `RouteResponse` is created via `Directions.calculate(...` which makes an HTTP request to the Directions API, `identifier` will always be present. Correct?

**Comment by jill-cardamon** [comment]
Yes it should always be present in that case.

**Comment by sundeepgupta** [comment]
Thank you
