### ISSUE TITLE
Incompatible versions of Turf between MapboxMaps 10.16.5 and MapboxDirections

### ISSUE THREAD

**Issue by f-gonzalez** [mapbox/mapbox-directions-swift#817]
MapboxMaps version 10.16.5 specifies the dependency Turf to be 2.7.0: https://github.com/mapbox/mapbox-maps-ios/blob/v10.16.5/MapboxMaps.podspec

While MapboxDirections [is on 2.6.1](https://github.com/mapbox/mapbox-maps-ios/blob/v10.16.5/MapboxMaps.podspec), so they can't be used together.

```
[!] CocoaPods could not find compatible versions for pod "Turf":
  In Podfile:
    MapboxDirections (= 2.11.1) was resolved to 2.11.1, which depends on
      Turf (~> 2.6.1)

    MapboxMaps (= 10.16.5) was resolved to 10.16.5, which depends on
      Turf (= 2.7.0)
```

**Comment by Udumft** [comment]
Hi @f-gonzalez! Thanks for flagging this. Indeed, there is currently no live version of Directions compatible with Turf 2.7.0. We'll schedule an update and I'll let you know when it's available.

**Comment by Udumft** [comment]
Hi @f-gonzalez! Directions [v2.12.0](https://github.com/mapbox/mapbox-directions-swift/releases/tag/v2.12.0) has been released and has updated Turf dependency.
I am going to close this ticket, but feel free to try it and reopen if that did not help.
