### ISSUE TITLE
Incompatible versions of Turf between MapboxMaps 11.4 and MapboxDirections 2.12

### ISSUE THREAD

**Issue by f-gonzalez** [mapbox/mapbox-directions-swift#824]
MapboxMaps version 11.4 specifies the dependency Turf to be 2.8.0: https://github.com/mapbox/mapbox-maps-ios/blob/v11.4.0/MapboxMaps.podspec

While MapboxDirections [is on 2.7](https://github.com/mapbox/mapbox-directions-swift/blob/main/Package.swift), so they can't be used together.

**Error**:
```
[!] CocoaPods could not find compatible versions for pod "Turf":
  In Podfile:
    MapboxDirections (= 2.12.0) was resolved to 2.12.0, which depends on
      Turf (~> 2.7.0)

    MapboxMaps (= 11.4.0) was resolved to 11.4.0, which depends on
      Turf (= 2.8.0)
```

**Comment by amzada** [comment]
Related issue: https://github.com/mapbox/mapbox-maps-ios/issues/2188#issuecomment-2127300086
